import {useEffect,useState} from 'react';import {InlineError} from './ui';
type Receipt={filename:string;sha256:string;bytes:number;receivedAt:string;author:string;timing:string;nativePublication:string;accepted:{noteId:string;eventId:string;pointer:string}[];rejected:{pointer:string;message:string}[];duplicate:boolean;rawText?:string};
async function call(url:string,body?:unknown){const r=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const value=await r.json();if(!r.ok)throw Error(value.error||'Intake failed');return value;}
export function NoteIntakePanel({exerciseId,eventId,observedTick,onChanged,prepared=false}:{exerciseId:string;eventId:string;observedTick:number;onChanged:()=>void;prepared?:boolean}){
 const [files,setFiles]=useState<Receipt[]>([]),[file,setFile]=useState<File|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[source,setSource]=useState<Receipt|null>(null),[note,setNote]=useState('The bulletin repeats the survey estimate. Treat these as one lineage, retain uncertainty, and try a smaller legal commitment before judging the decision. This is a rehearsal discussion prompt, not a learner score.');
 const load=async()=>setFiles(await call('/api/learning/intake'));
 useEffect(()=>{setFiles([]);setFile(null);setSource(null);setError(null);void load().catch(e=>setError(e.message));},[exerciseId]);
 const upload=async()=>{if(!file)return;setBusy(true);setError(null);try{const r:Receipt=await call('/api/learning/intake',{exerciseId,filename:file.name,text:await file.text()});setMessage(`${r.duplicate?'Duplicate file; original retained.':`${r.accepted.length} notes imported.`} ${r.rejected.length} rows quarantined with reasons.`);await load();onChanged();}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const savePrepared=async()=>{setBusy(true);setError(null);try{const text=JSON.stringify({schema:'replay.facilitator-notes/1',records:[{id:'presenter-note-'+crypto.randomUUID(),commandEventId:eventId,observedTick,text:note,sourceIds:[]}]},null,2);const r:Receipt=await call('/api/learning/intake',{exerciseId,filename:'presenter-review-note.json',text});setMessage(`${r.accepted.length} qualified review note saved. ${r.rejected.length} rows quarantined. Original decision unchanged.`);await load();onChanged();}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const template=()=>{const text=JSON.stringify({schema:'replay.facilitator-notes/1',records:[{id:'review-note-'+Date.now(),commandEventId:eventId,observedTick,text:'Fictional rehearsal note: compare the source lineage before interpreting this commitment. This is an instructor discussion prompt, not a score.',sourceIds:[]}]},null,2);const u=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='facilitator-notes.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
 return <details open={prepared||undefined}><summary>{prepared?'Record your interpretation':'Import facilitator notes or AAR excerpts'}</summary><p className="small muted">Import permitted public or synthetic JSON notes linked to this exact decision. Uploaded notes are always post-hoc and shared within this exercise’s side; they never establish what the participant knew then. Originals and explicit revisions are retained locally. Native catalog publication remains pending.</p>{prepared&&<div><label htmlFor="presenter-note" style={{display:'block',marginBottom:8,fontWeight:600}}>Your qualified review and next practice</label><textarea id="presenter-note" className="input" style={{display:'block',width:'100%',boxSizing:'border-box',font:'inherit',lineHeight:1.5,padding:12,minHeight:115}} rows={4} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/><p><button className="btn btn-primary" disabled={busy||!note.trim()} onClick={()=>void savePrepared()}>Save post-hoc review note</button></p><p className="small muted">Suggested rehearsal wording. Edit before saving; the resulting note records your actual signed-in identity and time. It is not instructor acceptance or a participant score.</p></div>}<div className="action-row"><button className="btn btn-sm" disabled={!eventId} onClick={template}>Download notes template for this decision</button><input type="file" accept=".json,application/json" aria-label="Facilitator notes JSON file" onChange={e=>setFile(e.target.files?.[0]??null)}/><button className="btn btn-sm" disabled={!file||busy} onClick={()=>void upload()}>{busy?'Importing…':'Import notes'}</button></div>{message&&<p role="status" className="small">{message}</p>}<InlineError message={error}/>{files.map(r=><details key={r.sha256}><summary>{r.filename} · {r.accepted.length} accepted / {r.rejected.length} quarantined</summary><p className="small">{r.receivedAt} · {r.author} · {r.timing}</p><code style={{overflowWrap:'anywhere'}}>{r.sha256}</code>{r.rejected.map((e,i)=><p className="small" key={i}>{e.pointer}: {e.message}</p>)}<p><button className="btn btn-sm" onClick={()=>void call('/api/learning/intake/'+r.sha256).then(setSource).catch(e=>setError(e.message))}>Inspect original file</button></p></details>)}{source&&<div><h4>{source.filename} · original</h4><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',fontSize:12}}>{source.rawText}</pre><button className="btn btn-sm" onClick={()=>setSource(null)}>Close source</button></div>}</details>
}
