import {modelPresentation} from '../model-presentation';
import {useState} from 'react';

type Claim={text:string;citations:string[];basis?:string};
export interface RecordedAnalysis {
 provenance:{retrievedAt:string;reviewStatus:string;originalRecordHash:string;newModelCalls:number};
 record:{exerciseId:string;eventId:string;generatedAt:string;hash:string;debrief:{headline:Claim;observations:Claim[];tradeoffs:Claim[];questions:Claim[];nextPractice:Claim[];limitations:Claim[]};references:{id:string;kind:string;availability:string;tick?:number;content:string}[];receipt:{id:string;modelReturned?:string}};
}
/** Portable native output: never inserted into the synthetic exercise or presented as a new run. */
export function RecordedAnalysisPanel({analysis,linkedToCase=false}:{analysis:RecordedAnalysis;linkedToCase?:boolean}){
 const [selected,setSelected]=useState<string|null>(null),r=analysis.record,source=r.references.find(x=>x.id===selected);
 const claim=(c:Claim,i:number)=><li key={i}><p>{c.text}</p><div className="action-row">{c.citations.map(id=><button key={id} className="btn btn-sm" onClick={()=>setSelected(id)} title={id}>Inspect {r.references.find(x=>x.id===id)?.kind??'reference'} · {id.slice(-12)}</button>)}</div>{c.basis&&<p className="small muted">Recorded basis: {c.basis}</p>}</li>;
 return <section><h3>Saved analysis · {modelPresentation(r.receipt)}</h3><p className="small muted">Recorded native output · {new Date(r.generatedAt).toLocaleString()}. {linkedToCase ? 'Saved analysis from this case.' : 'This separate native example was not generated for the authored synthetic rehearsal.'} Opening it makes no new model request.</p><h4>{r.debrief.headline.text}</h4><div className="action-row">{r.debrief.headline.citations.map(id=><button key={id} className="btn btn-sm" title={id} onClick={()=>setSelected(id)}>Inspect headline source · {id.slice(-12)}</button>)}</div>{(['observations','tradeoffs','questions','nextPractice','limitations'] as const).map(key=><details key={key}><summary>{({observations:'Recorded observations',tradeoffs:'Recorded tradeoffs',questions:'Questions for discussion',nextPractice:'Recorded next practice',limitations:'Model limitations'})[key]}</summary><ul className="plain-list">{r.debrief[key].map(claim)}</ul></details>)}{source&&<div className="source-detail"><h4>Exact saved citation · {source.kind}</h4><p>{source.content}</p><p className="small muted">{source.availability}{source.tick!==undefined?` · tick ${source.tick}`:''}</p><code style={{overflowWrap:'anywhere'}}>{source.id}</code><p><button className="btn btn-sm" onClick={()=>setSelected(null)}>Close saved citation</button></p></div>}<p className="small muted">{analysis.provenance.reviewStatus}. Reference identity and timing checks do not establish semantic correctness or learning improvement.</p><details><summary>Saved model receipt and provenance</summary><p>Receipt {r.receipt.id} · {modelPresentation(r.receipt)}</p><p>Retrieved read-only {analysis.provenance.retrievedAt}. New model calls: {analysis.provenance.newModelCalls}.</p><code style={{overflowWrap:'anywhere'}}>{r.hash}</code></details></section>;
}
