import {afterEach,expect,it} from 'vitest';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {GameService,type Session} from '../../src/server/service';import {DeterministicClient,type CompleteInput} from '../../src/inference';
const clean:(()=>void)[]=[];afterEach(()=>clean.splice(0).reverse().forEach(f=>f()));
const answer=(req:CompleteInput)=>{const c=JSON.parse(req.input),id=c.commandEventId;return {headline:{text:'A recorded order committed forces.',citations:[id]},observations:[{text:'The participant issued this order.',citations:[id],basis:'available-then'}],opponentPerspective:[],tradeoffs:[],questions:[{text:'What information supported the choice?',citations:[id]}],nextPractice:[{text:'Record the reason before the next order.',citations:['C5']}],limitations:[{text:'Criteria are provisional; this is an automated software fixture.',citations:[]}]};};
async function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'replay-debrief-authority-')),s=new GameService(dir);clean.push(()=>fs.rmSync(dir,{recursive:true,force:true}),()=>s.close());const identity={subject:'learner',name:'Learner',role:'commander' as const,organization:'Synthetic',mode:'kamiwaza' as const};const row=await s.create('Debrief authority','plains',identity),w=s.world(row.id);row.options.workroomId='room';for(let n=0;n<25;n++)s.tick(w);s.command(row.id,'blue',{type:'attack',targetID:null,troops:10},'fixture-order',identity);s.tick(w);const event=s.store.events(row.id).find(e=>e.kind==='command'&&e.actor===identity.subject)!;row.status='completed';row.kind='recorded';s.store.putExercise(row);const session:Session={identity,activeId:row.id,selectedSide:'blue',playbackTick:null};const resolved=()=>({identity,context:{workroomId:'room',fresh:true,canEdit:true,canRunAgents:true},nativeReceipts:[]} as any);return {s,w,event,session,resolved};}
it('cannot start native debrief inference without fresh native authority',async()=>{const f=await fixture(),client=new DeterministicClient({respond:answer});f.s.luna=client;await expect(f.s.debrief(f.session,f.event.id)).rejects.toMatchObject({status:403});const r=f.resolved();r.context.canRunAgents=false;await expect(f.s.debrief(f.session,f.event.id,async()=>r)).rejects.toMatchObject({status:403});expect(client.history).toHaveLength(0);});
it.each(['permission','subject','workroom','session','live-role','enrollment'])('discards without caching when %s changes during inference',async reason=>{
 const f=await fixture(),r=f.resolved();if(reason==='live-role'){f.w.row.status='running';f.session.identity.role='instructor';r.identity={...r.identity};}
 if(reason==='enrollment'){f.w.row.options.ownerSubject='another-owner';f.s.teams.enroll(f.w.row,f.session.identity,1);}
 const client=new DeterministicClient({respond:req=>{if(reason==='permission')r.context.canRunAgents=false;if(reason==='subject')r.identity={...r.identity,subject:'other'};if(reason==='workroom')r.context.workroomId='other';if(reason==='session')r.context.fresh=false;if(reason==='live-role')r.identity.role='commander';if(reason==='enrollment')f.s.teams.remove(f.w.row,'learner','another-owner');return answer(req);}});f.s.luna=client;
 await expect(f.s.debrief(f.session,f.event.id,async()=>r)).rejects.toMatchObject({status:403,extra:{receiptId:expect.any(String)}});expect(client.history).toHaveLength(1);expect(f.s.cachedDebrief(f.session,f.event.id)).toBeNull();const events=f.s.store.events(f.w.row.id);expect(events.some(e=>e.kind==='debrief_result_discarded'&&e.details.receiptId)).toBe(true);expect(events.some(e=>e.kind==='debrief_generated')).toBe(false);
});
it('coalesces paid generation but checks each waiting native session before delivery',async()=>{
 const f=await fixture(),first=f.resolved(),second=f.resolved();let release!:()=>void,started!:()=>void;const gate=new Promise<void>(r=>release=r),entered=new Promise<void>(r=>started=r);const client=new DeterministicClient({respond:answer});f.s.luna={model:client.model,complete:async(req:CompleteInput)=>{started();await gate;return client.complete(req);}} as any;
 const a=f.s.debrief(f.session,f.event.id,async()=>first);await entered;let waitingChecked!:()=>void;const waiting=new Promise<void>(r=>waitingChecked=r);const b=f.s.debrief(structuredClone(f.session),f.event.id,async()=>{waitingChecked();return second;});const captured=b.catch(e=>e);await waiting;await new Promise(r=>setTimeout(r,0));second.context.canRunAgents=false;release();const [ok,denied]=await Promise.all([a,captured]);expect(ok.status).toBe('generated');expect(denied.status).toBe(403);expect(client.history).toHaveLength(1);expect(f.s.cachedDebrief(f.session,f.event.id)?.record.receipt.id).toBe(ok.record.receipt.id);
 const cached=await f.s.debrief(f.session,f.event.id,async()=>first);expect(cached.status).toBe('cached');expect(client.history).toHaveLength(1);
});
