import {afterEach,expect,it,vi} from 'vitest';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {AgentAuthority} from '../../src/server/native-agent-bindings';import {GameService} from '../../src/server/service';import {DeterministicClient} from '../../src/inference/index';
const context=()=>({identity:{subject:'user'},context:{workroomId:'room',fresh:true,canEdit:true,canRunAgents:true,validatedAt:'today'},nativeReceipts:[{clientRequestId:'auth-receipt'}],platformClient:{searchOntology:vi.fn(async()=>({data:{facts:[{fact_uuid:'f1',content:'Current reports supersede earlier estimates',metadata:{private:'must not copy'}}],sources:[{fact_uuid:'f1',sources:[{source_id:'src1'}]}],total_count:1,query:'rules'},receipt:{requestId:'native-search'}}))}} as any);
it('revalidates exact native scope and caches only bounded actual native retrieval',async()=>{const r=context(),audit=vi.fn(),a=new AgentAuthority({subject:'user',workroomId:'room'},async()=>r,audit,'ontology');expect(await a.check()).toBe(true);expect(await a.domain()).toMatchObject({status:'native',requestId:'native-search',facts:[{id:'f1',sourceIds:['src1']}]});await a.domain();expect(r.platformClient.searchOntology).toHaveBeenCalledTimes(1);expect(r.platformClient.searchOntology).toHaveBeenCalledWith('ontology',expect.objectContaining({group_ids:['room'],max_results:8}),{workroomId:'room'});expect(JSON.stringify(audit.mock.calls)).not.toContain('must not copy');r.context.canRunAgents=false;expect(await a.check()).toBe(false);expect((await a.domain()).status).toBe('unavailable');});
it.each(['subject','workroom','stale'])('fails closed when %s changes',async key=>{const r=context();if(key==='subject')r.identity.subject='other';if(key==='workroom')r.context.workroomId='other';if(key==='stale')r.context.fresh=false;expect(await new AgentAuthority({subject:'user',workroomId:'room'},async()=>r,()=>{}).check()).toBe(false);});
it('reports a failed native query as unavailable, never synthesized native facts',async()=>{const r=context();r.platformClient.searchOntology.mockRejectedValue(new Error('private'));const a=new AgentAuthority({subject:'user',workroomId:'room'},async()=>r,()=>{},'ontology');await a.check();expect(await a.domain()).toEqual(expect.objectContaining({status:'unavailable'}));expect(JSON.stringify(await a.domain())).not.toContain('private');});
const clean:(()=>void)[]=[];afterEach(()=>clean.splice(0).reverse().forEach(f=>f()));
async function nativeWorld(){const d=fs.mkdtempSync(path.join(os.tmpdir(),'native-authority-')),s=new GameService(d);clean.push(()=>fs.rmSync(d,{recursive:true,force:true}),()=>s.close());const row=await s.create('Native scope','plains');const w=s.world(row.id);for(let i=0;i<25;i++)s.tick(w);w.row.options.workroomId='room';w.row.options.ownerSubject='user';w.row.agentEnabled=true;s.store.putExercise(w.row);return{s,w};}
it('a native controller without an initiating resolver cannot spend',async()=>{const{s,w}=await nativeWorld();const client=new DeterministicClient();s.luna=client;await s.runOpponent(w);expect(client.history).toHaveLength(0);expect(w.row.agentEnabled).toBe(false);expect(s.store.events(w.row.id).at(-1)?.kind).toBe('agent_authorization_denied');});
it('revocation while inference is in flight preserves its receipt and prevents a player order',async()=>{const{s,w}=await nativeWorld(),r=context();s.bindAgentAuthority({identity:{subject:'user',name:'User',role:'instructor',organization:'Lab',mode:'kamiwaza'},activeId:w.row.id,playbackTick:null,selectedSide:'blue'},'opponent',async()=>r);
 s.luna=new DeterministicClient({respond:()=>{r.context.canRunAgents=false;return {summary:'Selected expansion',sourceIds:[],done:true,calls:[{tool:'submit_order',arguments:JSON.stringify({intent:{type:'attack',targetID:null,troops:10}})}]};}});await s.runOpponent(w);expect(w.row.agentEnabled).toBe(false);expect(s.store.pending(w.row.id)).toHaveLength(0);const ev=s.store.events(w.row.id);expect(ev.some(e=>e.kind==='model_decision'&&e.details.receipt?.id)).toBe(true);expect(ev.some(e=>e.kind==='model_result_discarded')).toBe(true);});

it('stops a player controller if the native seat changes to intelligence',async()=>{const r=context();r.identity.role='intelligence';expect(await new AgentAuthority({subject:'user',workroomId:'room',canCommand:true},async()=>r,()=>{}).check()).toBe(false);});
