import {afterEach,describe,expect,it} from 'vitest';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {GameService,type Identity,type Session,CURRICULUM} from '../../src/server/service';import {buildDebriefContext} from '../../src/learning/debrief';import {parseFacilitatorNotes} from '../../src/learning/intake';
console.debug=()=>{};const clean:(()=>void)[]=[];afterEach(()=>clean.splice(0).reverse().forEach(f=>f()));
const user:Identity={subject:'presenter',name:'Presenter',role:'instructor',organization:'Rehearsal',mode:'local-demo'};
const service=()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'replay-showcase-tests-')),s=new GameService(dir);clean.push(()=>fs.rmSync(dir,{recursive:true,force:true}),()=>s.close());return s};
const session=(id:string):Session=>({identity:user,activeId:id,playbackTick:null,selectedSide:'blue'});
describe('prepared instructor demonstration',()=>{
 it('installs once, reloads exact evidence, and makes an independent legal practice action',async()=>{const s=service(),a=await s.prepareShowcase(user,null),again=await s.prepareShowcase(user,null);expect(again.duplicate).toBe(true);expect(again.exerciseId).toBe(a.exerciseId);const count=s.store.events(a.exerciseId).length,original=s.world(a.exerciseId).engine.state().fingerprint;expect(count).toBe(11);expect(s.decisionRetrieval(session(a.exerciseId),a.selectedEventId).retrieval!.steps.length).toBeGreaterThan(0);expect(s.learningRecord(a.exerciseId).exercise.ownerSubject).toBeUndefined();const branch=await s.branch(a.exerciseId,a.forkTick,'blue',user),w=s.world(branch.id);s.command(branch.id,'blue',{type:'attack',targetID:null,troops:Math.floor(w.engine.player('blue').troops()*.1)},'showcase-practice-order',user);s.tick(w);expect(s.store.events(branch.id).some(e=>e.kind==='command'&&e.actor==='presenter')).toBe(true);expect(s.world(a.exerciseId).engine.state().fingerprint).toBe(original);expect(s.store.events(a.exerciseId)).toHaveLength(count);expect(s.learningRecord(branch.id).exercise.ownerSubject).toBe('presenter');});
 it('separates participant and workroom prepared copies and refuses hash drift',async()=>{const s=service(),a=await s.prepareShowcase(user,'room-a'),b=await s.prepareShowcase(user,'room-b');expect(a.exerciseId).not.toBe(b.exerciseId);s.world(a.exerciseId).row.options.showcaseSha256='changed';s.store.putExercise(s.world(a.exerciseId).row);await expect(s.prepareShowcase(user,'room-a')).rejects.toThrow(/conflicts/);});
 it('keeps the unattended default exercise still until a participant opens it',async()=>{const s=service();await s.init(false);const w=s.world(s.defaultSession().activeId),tick=w.engine.game.ticks();for(let i=0;i<100;i++)s.tick(w);expect(w.engine.game.ticks()).toBe(tick);await s.overview(s.defaultSession());s.tick(w);expect(w.engine.game.ticks()).toBe(tick+1);});
 it('refuses branching from an eliminated state without adding a new exercise',async()=>{const s=service(),a=await s.prepareShowcase(user,null),w=s.world(a.exerciseId);const fixture=s.record(a.exerciseId); // Exercise creation side effects are checked around a controlled eliminated restore boundary.
 const {ReplayEngine}=await import('../../src/engine/engine');const {vi}=await import('vitest');const restored=await ReplayEngine.restore(fixture,a.forkTick);const realState=restored.state.bind(restored);const spy=vi.spyOn(ReplayEngine,'restore').mockResolvedValue(restored);vi.spyOn(restored,'state').mockImplementation((...args:any[])=>({...realState(...args),spawning:false,players:realState().players.map(p=>({...p,alive:p.side!=='blue'}))}));const before=s.store.exercises().length;try{await expect(s.branch(a.exerciseId,a.forkTick,'blue',user)).rejects.toThrow(/earlier tick/);expect(s.store.exercises()).toHaveLength(before);}finally{spy.mockRestore();vi.restoreAllMocks();}});
});
describe('source note intake',()=>{
 it('ingests changed notes, preserves originals, quarantines bad rows and marks the derived context changed',async()=>{const s=service(),a=await s.prepareShowcase(user,null),who=session(a.exerciseId),before=buildDebriefContext(s.learningRecord(a.exerciseId),a.selectedEventId,CURRICULUM);const text=JSON.stringify({schema:'replay.facilitator-notes/1',records:[{id:'note-1',commandEventId:a.selectedEventId,observedTick:320,text:'The second source repeats the first; ask the participant what they checked.'},{id:'bad',commandEventId:'other-exercise',observedTick:9000,text:'Invalid source association'}]});const receipt=s.intakeNotes(who,{exerciseId:a.exerciseId,filename:'notes.json',text});expect(receipt.accepted).toHaveLength(1);expect(receipt.rejected).toHaveLength(1);expect(s.intakeNotes(who,{exerciseId:a.exerciseId,filename:'notes.json',text}).duplicate).toBe(true);expect(s.intakeSource(who,receipt.sha256).rawText).toBe(text);const after=buildDebriefContext(s.learningRecord(a.exerciseId),a.selectedEventId,CURRICULUM);expect(after.prompt.input).not.toBe(before.prompt.input);expect(after.references.find(r=>r.kind==='facilitator-note')?.availability).toBe('hindsight');const correction=JSON.stringify({schema:'replay.facilitator-notes/1',records:[{id:'note-2',revisionOf:'note-1',commandEventId:a.selectedEventId,observedTick:320,text:'Correction: use the release cutoff before discussing the later source.'}]});s.intakeNotes(who,{exerciseId:a.exerciseId,filename:'correction.json',text:correction});const revised=buildDebriefContext(s.learningRecord(a.exerciseId),a.selectedEventId,CURRICULUM);expect(revised.references.find(r=>r.id===receipt.accepted[0].eventId)?.content).toContain('Superseded by note note-2');expect(s.noteIntakeHistory(who)).toHaveLength(2);});
 it('rejects malformed data and cross-exercise intake without changing evidence',async()=>{const s=service(),a=await s.prepareShowcase(user,null),count=s.store.events(a.exerciseId).length;expect(()=>parseFacilitatorNotes('notes.json','{')).toThrow(/Invalid JSON/);expect(()=>s.intakeNotes(session(a.exerciseId),{exerciseId:'other',filename:'notes.json',text:'{}'})).toThrow(/Exercise changed/);expect(s.store.events(a.exerciseId)).toHaveLength(count);});
});
