import http from 'node:http';
import https from 'node:https';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';

const REQUEST_LIMIT = 16 * 1024;
const RESPONSE_LIMIT = 256 * 1024;
const TIMEOUT_MS = 20_000;
const FORWARDED = ['authorization', 'x-workroom-id', 'content-type', 'accept'];

function upstreamURL(value) {
  try {
    if (typeof value !== 'string' || !/^https?:\/\/[^/?#\\@\s]+\/mcp$/.test(value)) throw new Error();
    const url = new URL(value);
    if (!['http:', 'https:'].includes(url.protocol) || url.pathname !== '/mcp' || url.username || url.password || url.search || url.hash) throw new Error();
    return url;
  } catch { throw new Error('REPLAY_MCP_UPSTREAM must be an http(s) URL with exact /mcp and no userinfo, query or fragment'); }
}

/** No environment reads or sockets on import. timeoutMs may only shorten the production deadline. */
export function createProxy({upstream, timeoutMs = TIMEOUT_MS}) {
  const target = upstreamURL(upstream);
  if (!Number.isInteger(timeoutMs) || timeoutMs < 1 || timeoutMs > TIMEOUT_MS) throw new Error('Invalid proxy timeout');
  const transport = target.protocol === 'https:' ? https : http;
  const server = http.createServer({maxHeaderSize: REQUEST_LIMIT, requestTimeout: TIMEOUT_MS, headersTimeout: TIMEOUT_MS}, (req, res) => {
    res.setHeader('Cache-Control', 'no-store');
    res.setHeader('Pragma', 'no-cache');
    res.setHeader('X-Content-Type-Options', 'nosniff');
    res.setHeader('Content-Type', 'application/json; charset=utf-8');
    const send = (status, body) => {
      if (res.writableEnded || res.destroyed) return;
      res.statusCode = status;
      if (status >= 400) res.setHeader('Connection', 'close');
      res.end(body === undefined ? undefined : typeof body === 'string' || Buffer.isBuffer(body) ? body : JSON.stringify(body));
    };
    if (req.url === '/health' && req.method === 'GET') return send(200, {status: 'ok'});
    if (req.url !== '/mcp' && req.url !== '/health') return send(404, {error: 'Not found'});
    if (req.url !== '/mcp' || req.method !== 'POST') {
      res.setHeader('Allow', req.url === '/health' ? 'GET' : 'POST');
      return send(405, {error: 'Method not allowed'});
    }

    let outgoing;
    let incoming;
    let done = false;
    const cleanup = () => { clearTimeout(deadline); outgoing?.destroy(); incoming?.destroy(); };
    const fail = (status, message) => {
      if (done) return;
      done = true;
      cleanup();
      req.resume();
      send(status, {error: message});
    };
    // Wall-clock bound includes client upload and the entire upstream response, not just idle time.
    const deadline = setTimeout(() => fail(504, 'Proxy request timed out'), timeoutMs);
    deadline.unref();
    res.once('close', () => {done = true; cleanup();});
    req.once('error', () => fail(400, 'Invalid request'));
    if (Number(req.headers['content-length']) > REQUEST_LIMIT) return fail(413, 'Request too large');
    const chunks = [];
    let size = 0;
    req.on('data', chunk => {
      if (done) return;
      size += chunk.length;
      if (size > REQUEST_LIMIT) return fail(413, 'Request too large');
      chunks.push(chunk);
    });
    req.once('end', () => {
      if (done) return;
      const body = Buffer.concat(chunks, size);
      const headers = {};
      for (const name of FORWARDED) if (typeof req.headers[name] === 'string') headers[name] = req.headers[name];
      // Host and framing are generated by Node for the fixed target; caller routing headers are ignored.
      headers['content-length'] = String(body.length);
      outgoing = transport.request(target, {method: 'POST', headers, agent: false}, upstreamRes => {
        incoming = upstreamRes;
        if (done) return cleanup();
        const status = upstreamRes.statusCode ?? 502;
        // Node's request API never follows redirects. No upstream status text/body/header is reflected.
        if (status >= 300 && status < 400) return fail(502, 'Upstream redirect refused');
        if (status >= 400) return fail(status <= 599 ? status : 502, 'Upstream request failed');
        if (status !== 200 && status !== 202) return fail(502, 'Unsupported upstream response');
        if (upstreamRes.headers['content-encoding'] && upstreamRes.headers['content-encoding'] !== 'identity') return fail(502, 'Unsupported upstream response');
        if (Number(upstreamRes.headers['content-length']) > RESPONSE_LIMIT) return fail(502, 'Upstream response too large');
        const responseChunks = [];
        let responseSize = 0;
        upstreamRes.on('data', chunk => {
          if (done) return;
          responseSize += chunk.length;
          if (responseSize > RESPONSE_LIMIT) return fail(502, 'Upstream response too large');
          responseChunks.push(chunk);
        });
        upstreamRes.once('error', () => fail(502, 'Upstream request failed'));
        upstreamRes.once('end', () => {
          if (done) return;
          let response = Buffer.concat(responseChunks, responseSize);
          if (status === 200) {
            if (!/^application\/(?:[\w.+-]+\+)?json(?:\s*;|$)/i.test(upstreamRes.headers['content-type'] ?? '')) return fail(502, 'Unsupported upstream response');
            try {
              const parsed = JSON.parse(response.toString('utf8'));
              // Keep JSON-RPC error correlation, but discard arbitrary adapter error messages/data.
              if (parsed && typeof parsed === 'object' && !Array.isArray(parsed) && 'error' in parsed) {
                const requestId = JSON.parse(body.toString('utf8'))?.id;
                response = Buffer.from(JSON.stringify({jsonrpc: '2.0', id: typeof requestId === 'string' || typeof requestId === 'number' ? requestId : null,
                  error: {code: Number.isInteger(parsed.error?.code) ? parsed.error.code : -32603, message: 'Upstream request failed'}}));
              }
            } catch { return fail(502, 'Invalid upstream JSON'); }
          }
          done = true;
          clearTimeout(deadline);
          send(status, status === 202 ? undefined : response);
        });
      });
      outgoing.once('error', () => fail(502, 'Upstream request failed'));
      outgoing.end(body);
    });
  });
  // Prevent parser diagnostics, which can contain raw request bytes, from being logged or reflected.
  server.on('clientError', (_error, socket) => socket.end('HTTP/1.1 400 Bad Request\r\nConnection: close\r\nContent-Length: 0\r\nCache-Control: no-store\r\n\r\n'));
  return server;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  try {
    const port = Number(process.env.PORT ?? '5181');
    if (!Number.isInteger(port) || port < 1 || port > 65535) throw new Error('Invalid port');
    const server = createProxy({upstream: process.env.REPLAY_MCP_UPSTREAM});
    server.on('error', () => { process.stderr.write('MCP proxy could not start\n'); process.exitCode = 1; });
    server.listen(port, '0.0.0.0');
    for (const signal of ['SIGINT', 'SIGTERM']) process.once(signal, () => {server.close(); server.closeAllConnections();});
  } catch { process.stderr.write('MCP proxy configuration is invalid\n'); process.exitCode = 1; }
}
