import {describe,it,expect} from 'vitest';
import {buildDebriefContext,validateDebrief} from '../../src/learning/debrief';
import {retrieveDecision} from '../../src/learning/decision-retrieval';
import {curriculum,liveAttempt,order,report} from './fixtures';
describe('current-decision graph retrieval',()=>{
 it('follows real typed edges, carries source hashes and supplies exactly selected snippets',()=>{const r=liveAttempt('g'),ctx=buildDebriefContext(r,'g-o3',curriculum),t=ctx.retrieval!;expect(t.steps.length).toBeGreaterThan(0);expect(t.steps.every(s=>t.edges.some(e=>e.id===s.edgeId&&e.source===s.from&&e.target===s.to))).toBe(true);expect(t.nodes.every(n=>n.source.sha256.length===64)).toBe(true);expect(t.steps.some(s=>s.relation==='supersedes'&&s.from==='g-r2'&&s.to==='g-r1')).toBe(true);expect(JSON.parse(ctx.prompt.input).references.map((x:any)=>x.id)).toEqual(t.sentReferenceIds);expect(t.excerpts.map(x=>x.text)).toEqual(JSON.parse(ctx.prompt.input).references.map((x:any)=>x.content));});
 it('scope excludes opposing private records and can exclude all hindsight',()=>{const r=liveAttempt('g');r.reports.push(report('red-secret',1,undefined,'red'));const ctx=buildDebriefContext(r,'g-o2',curriculum,{retrieval:{includeHindsight:false}});expect(JSON.stringify(ctx.retrieval)).not.toContain('red-secret');expect(ctx.retrieval!.nodes.every(n=>n.availability!=='hindsight')).toBe(true);expect(ctx.sentReferenceIds).not.toContain('g-r2');});
 it('a source revision, outage and mapping change alter real paths or confidence',()=>{const r=liveAttempt('g'),ctx=buildDebriefContext(r,'g-o3',curriculum);expect(ctx.retrieval!.confidence.currency.find(x=>x.id==='g-r1')?.status).toBe('superseded');const missing=retrieveDecision(r,'g-o3',ctx.references,{unavailableSourceIds:['g-r2']});expect(missing.nodeIds).not.toContain('g-r2');expect(missing.confidence.missingEvidence).toContain('Source unavailable: g-r2');const changed=retrieveDecision(r,'g-o3',ctx.references,{mapping:{version:'reviewed-test/2',relations:{supersedes:null}}});expect(changed.edges.some(e=>e.relation==='supersedes')).toBe(false);expect(changed.graphSha256).not.toBe(ctx.retrieval!.graphSha256);});
 it('never validates a known reference removed from the bounded prompt',()=>{const r=liveAttempt('g');for(let i=0;i<100;i++)r.reports.push(report('extra-'+i,1));const ctx=buildDebriefContext(r,'g-o2',curriculum,{maxChars:2400});const omitted=ctx.references.find(x=>!ctx.sentReferenceIds!.includes(x.id))!;expect(omitted).toBeDefined();const bad={headline:{text:'An observation.',citations:[omitted.id]},observations:[],opponentPerspective:[],tradeoffs:[],questions:[],nextPractice:[],limitations:[{text:'Criteria are provisional.',citations:[]}]};expect(validateDebrief(bad,ctx).errors.some(e=>e.includes('unknown citation'))).toBe(true);expect(ctx.prompt.input.length).toBeLessThanOrEqual(2400);});
 it('reports missing reasons without inventing confidence or personal traits',()=>{const ctx=buildDebriefContext(liveAttempt('g'),'g-o2',curriculum);expect(ctx.retrieval!.confidence.missingEvidence).toContain('No written participant reason at the decision.');expect(ctx.retrieval!.confidence.eventLikelihood).toBe('not estimated');expect(ctx.retrieval!.confidence.validationStatus).toContain('no semantic or instructor acceptance');});
});
