import {afterEach,expect,it} from 'vitest';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';
import {GameService,type Session} from '../../src/server/service';import {assessment,saveJudgment,exportAssessment,redact} from '../../src/review/assessment';
const clean:(()=>void)[]=[];afterEach(()=>clean.splice(0).reverse().forEach(f=>f()));
async function setup(){const d=fs.mkdtempSync(path.join(os.tmpdir(),'instructor-review-')),s=new GameService(d);clean.push(()=>fs.rmSync(d,{recursive:true,force:true}),()=>s.close());const row=await s.create('Assessment','plains');const session={...s.defaultSession('instructor'),activeId:row.id} as Session;const report=s.store.reports(row.id).find(r=>r.side==='blue');return{s,d,row,session,report};}
const judgment=(id:string,overrides:any={})=>({criterionId:'C1',baseVersion:0,score:2,disposition:'confirmed',rationale:'Recorded source identification is supported by this report.',evidenceIds:[id],...overrides});
it('appends corrections and preserves versions across service restart',async()=>{const{s,d,row,session,report}=await setup();const a=saveJudgment(s,session,judgment(report.id));const b=saveJudgment(s,session,judgment(report.id,{baseVersion:1,score:null,disposition:'contested',rationale:'The observation exists but the interpretation requires instructor discussion.'}));expect(b.previousId).toBe(a.id);expect(()=>saveJudgment(s,session,judgment(report.id,{baseVersion:1}))).toThrow(/newer judgment/);const reopened=new GameService(d);clean.push(()=>reopened.close());await reopened.init(false);const out=assessment(reopened,session);expect(out.history).toHaveLength(2);expect(out.current[0].judgment?.score).toBeNull();expect(out.current[0].judgment?.version).toBe(2);});
it('rejects spoofed role, unknown criterion, cross-exercise citations and scores without observations',async()=>{const{s,row,session,report}=await setup();const learner={...session,identity:{...session.identity,role:'commander' as const}};expect(()=>saveJudgment(s,learner,{...judgment(report.id),role:'instructor'})).toThrow(/Instructor/);expect(()=>saveJudgment(s,session,judgment(report.id,{criterionId:'C999'}))).toThrow(/Unknown/);const other=await s.create('Someone else','plains');expect(()=>saveJudgment(s,session,judgment(s.store.reports(other.id)[0].id))).toThrow(/this exercise/);expect(()=>saveJudgment(s,session,judgment(report.id,{evidenceIds:[],score:0}))).toThrow(/observable evidence/);expect(()=>saveJudgment(s,session,judgment(report.id,{disposition:'withheld'}))).toThrow(/score requires/);const withheld=saveJudgment(s,session,judgment(report.id,{evidenceIds:[],score:null,disposition:'withheld',rationale:'Unobserved: no participant source assessment was recorded.'}));expect(withheld.score).toBeNull();});
it('exports an actual digest and only the authorized exercise; live learners do not get opposing private records or canonical inputs',async()=>{const{s,row,session}=await setup();const other=await s.create('Other private exercise','plains');s.store.event(other.id,1,'assessment','other-person','private other record',{privateNote:'do not export'});s.store.event(row.id,1,'staff_update','red-controller','opposing private assessment',{password:'must-not-leak'},'red');s.store.event(row.id,1,'assessment','user','own observation',{token:'secret-token'},'blue');
 const student={...session,identity:{...session.identity,role:'commander' as const}};const live=exportAssessment(s,student);const txt=JSON.stringify(live);expect(txt).not.toContain('opposing private assessment');expect(txt).not.toContain('Other private exercise');expect(txt).not.toContain('secret-token');expect(live.payload.engine.canonicalRecord).toBeNull();
 const full=exportAssessment(s,session);expect(full.payload.engine.canonicalRecord?.turns.length).toBe(1);expect(JSON.stringify(full)).toContain('opposing private assessment');expect(JSON.stringify(full)).not.toContain('must-not-leak');expect(full.sha256).toBe(createHash('sha256').update(JSON.stringify(full.payload)).digest('hex'));
 s.world(row.id).row.status='completed';expect(exportAssessment(s,student).payload.engine.canonicalRecord?.turns.length).toBe(1);
});

it('includes failed and unrendered inference receipts only for the fully released exercise',async()=>{
 const {s,row,session}=await setup();
 const reserve=(id:string)=>s.ledger.reserve({purpose:'opponent decision',context:{exerciseId:id,side:'red'},modelRequested:'stub',reservedMicro:100});
 const own=reserve(row.id),other=reserve('another-exercise');
 s.ledger.release(own.id,{durationMs:1,httpStatus:400,errorCode:'http_400'});
 expect(exportAssessment(s,session).payload.receipts.map(r=>r.id)).toEqual([own.id]);
 expect(exportAssessment(s,{...session,identity:{...session.identity,role:'commander'}}).payload.receipts).toEqual([]);
 expect(exportAssessment(s,session).payload.receipts.map(r=>r.id)).not.toContain(other.id);
});

it('retains numeric usage metrics without allowing credentials through metric-shaped fields',()=>{
 expect(redact({inputTokens:3123,outputTokens:171,cachedInputTokens:null,token:'hidden',refreshToken:123,secret:7,nested:{outputTokens:'credential',inputTokens:{password:'hidden'},cachedInputTokens:-1,authorization:'hidden'}})).toEqual({inputTokens:3123,outputTokens:171,cachedInputTokens:null,nested:{}});
});
