/** Deterministic traversal of the selected exercise's evidence. No I/O or native graph claims. */
import {createHash} from 'node:crypto';
import {observedTick,rationaleFor,sourceStatusAt} from './evidence';
import {projectEvidenceRecords} from '../scenarios/evidence-records';
import type {DebriefReference,ExerciseRecord} from './types';
export type Relation='available_to_order'|'recorded_rationale'|'observed_effect'|'opponent_action'|'tool_receipt'|'later_evidence'|'evaluation_criterion'|'source_guidance'|'supersedes'|'derived-from'|'disputes'|'cites';
export interface DecisionNode {id:string;type:string;label:string;availability:DebriefReference['availability'];tick?:number;source:{exerciseId:string;recordId:string;kind:string;sha256:string;locator:string;parentSourceId?:string};excerpt:string;}
export interface DecisionEdge {id:string;source:string;target:string;relation:Relation;mappingId:string;}
export interface EvidenceConfidence {method:'calculated evidence basis; not a probability or instructor score';label:string;sourceQuality:string[];currency:{id:string;status:string;supersededBy?:string}[];independentLineages:{entityId:string;rootId:string;reportIds:string[]}[];conflicts:{id:string;withIds:string[]}[];missingEvidence:string[];assumptions:string[];alternatives:string[];wouldChangeIf:string[];validationStatus:string;eventLikelihood:'not estimated';}
export interface DecisionRetrieval {schema:'replay.decision-retrieval/1';mode:'calculated live retrieval'|'saved retrieval replay';exerciseId:string;branch:{parentId:string|null;forkTick:number|null};side:string;observedTick:number;graphSha256:string;mappingVersion:string;policy:{maxDepth:number;maxReferences:number;includeHindsight:boolean};seedIds:string[];nodes:DecisionNode[];edges:DecisionEdge[];nodeIds:string[];edgeIds:string[];steps:{step:number;depth:number;edgeId:string;from:string;to:string;relation:Relation}[];selectedReferenceIds:string[];sentReferenceIds:string[];excerpts:{id:string;text:string;sourceSha256:string;availability:DebriefReference['availability']}[];confidence:EvidenceConfidence;missingSourceIds:string[];}
export interface RetrievalOptions {includeHindsight?:boolean;maxReferences?:number;unavailableSourceIds?:string[];mapping?:{version:string;relations:Partial<Record<string,Relation|null>>};}
const hash=(x:unknown)=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
const RELATIONS:Record<string,Relation>={'supersedes':'supersedes','derived-from':'derived-from','disputes':'disputes'};
export function retrieveDecision(record:ExerciseRecord,eventId:string,refs:DebriefReference[],options:RetrievalOptions={}):DecisionRetrieval{
 const command=record.events.find(e=>e.id===eventId&&e.kind==='command'&&e.details.origin==='human');if(!command)throw Error('Human command not found in this exercise');
 const side=command.side??record.exercise.humanSide??'blue',at=observedTick(command),includeHindsight=options.includeHindsight!==false,maxReferences=Math.max(1,Math.min(options.maxReferences??40,40)),unavailable=new Set(options.unavailableSourceIds??[]);
 const nodes:DecisionNode[]=refs.filter(r=>(includeHindsight||r.availability!=='hindsight')&&!unavailable.has(r.id)).map(r=>{
  const sourceReport=record.reports.find(x=>x.id===r.id),event=record.events.find(e=>e.id===r.id||r.id.startsWith(e.id+':'));
  // References originate in the strict debrief projection; raw event details never enter model snippets.
  const raw=sourceReport??event??r;return {id:r.id,type:r.kind,label:r.content.slice(0,95),availability:r.availability,tick:r.tick,source:{exerciseId:record.exercise.id,recordId:sourceReport?.id??event?.id??r.id,kind:sourceReport?'report':event?'event':'curriculum',sha256:hash(raw),locator:sourceReport?`/reports/${record.reports.indexOf(sourceReport)}`:event?`/events/${record.events.indexOf(event)}`:`/curriculum/${r.id}`,...(sourceReport?.parentSourceId?{parentSourceId:sourceReport.parentSourceId}:{})},excerpt:r.content};
 });
 const ids=new Set(nodes.map(n=>n.id)),edges:DecisionEdge[]=[],mapped={...RELATIONS,...options.mapping?.relations};
 const link=(source:string,target:string,relation:Relation,mappingId:string)=>{if(source===target||!ids.has(source)||!ids.has(target))return;const id=hash([source,target,relation,mappingId]).slice(0,24);if(!edges.some(e=>e.id===id))edges.push({id,source,target,relation,mappingId});};
 for(const r of refs){
  const relation:Relation=(r.kind==='rationale'||r.kind==='facilitator-note')?'recorded_rationale':r.kind==='engine_observation'?'observed_effect':r.kind==='model_decision'?'opponent_action':r.kind==='tool_result'?'tool_receipt':r.kind==='criterion'?'evaluation_criterion':r.kind==='curriculum-source'?'source_guidance':r.availability==='hindsight'?'later_evidence':'available_to_order';
  link(eventId,r.id,relation,`reference-kind:${r.kind}/${r.availability}`);
 }
 for(const r of record.reports){
  if(r.supersedes&&mapped.supersedes)link(r.id,r.supersedes,mapped.supersedes,'report.supersedes');
  for(const rel of r.packet?.links??[]){const type=mapped[rel.kind];if(type)link(r.id,rel.reportId,type,'packet.links.'+rel.kind);}
 }
 for(const id of command.details.sourceIds??[])link(eventId,id,'cites','command.sourceIds');
 const visited=ids.has(eventId)?[eventId]:[],traversed:string[]=[],steps:DecisionRetrieval['steps']=[];let frontier=[...visited];
 // Favor explicitly cited reports and their lineage, then observed inputs, then labelled hindsight and criteria.
 const priority=(e:DecisionEdge)=>['cites','supersedes','derived-from','disputes','recorded_rationale','available_to_order','observed_effect','opponent_action','tool_receipt','later_evidence','evaluation_criterion','source_guidance'].indexOf(e.relation);
 for(let depth=1;depth<=2;depth++){const next:string[]=[];for(const from of frontier){for(const edge of edges.filter(e=>e.source===from).sort((a,b)=>priority(a)-priority(b))){if(visited.length>=maxReferences&&!visited.includes(edge.target))continue;traversed.push(edge.id);steps.push({step:steps.length+1,depth,edgeId:edge.id,from,to:edge.target,relation:edge.relation});if(!visited.includes(edge.target)){visited.push(edge.target);next.push(edge.target);}}}frontier=next;}
 const selected=visited.map(id=>nodes.find(n=>n.id===id)!),reports=record.reports.filter(r=>r.side===side&&r.tick<=at&&!unavailable.has(r.id)&&visited.includes(r.id));
 const projected=projectEvidenceRecords(reports),currency=projected.map(r=>({id:r.id,...sourceStatusAt(reports,r.id,at),...(r.evidenceStatus?{status:r.evidenceStatus,supersededBy:r.supersededBy}:{})}));
 const lineages=new Map<string,{entityId:string;rootId:string;reportIds:string[]}>();for(const r of projected){if(currency.find(x=>x.id===r.id)?.status==='superseded')continue;const root=r.packet?.lineageRootId??r.id,entity=r.packet?.entityId??'unspecified';const key=entity+':'+root;const v=lineages.get(key)??{entityId:entity,rootId:root,reportIds:[]};v.reportIds.push(r.id);lineages.set(key,v);}
 const rationale=rationaleFor(command,record.events),conflicts=projected.filter(r=>r.disputedWith?.length).map(r=>({id:r.id,withIds:r.disputedWith!}));
 const missing=[...(!rationale||rationale.form==='citation-only'?['No written participant reason at the decision.']:[]),...(!command.details.observation?['Client-returned observation snapshot absent; server cutoff is not proof of displayed state.']:[]),...(!reports.length?['No retrieved same-side report at this cutoff.']:[]),...([...unavailable].filter(id=>refs.some(r=>r.id===id)).map(id=>'Source unavailable: '+id))];
 const confidence:EvidenceConfidence={method:'calculated evidence basis; not a probability or instructor score',label:conflicts.length?'Conflicting source claims':missing.length?'Limited by missing evidence':'Recorded evidence available; interpretation needs review',sourceQuality:[command.details.synthetic?'Authored fictional rehearsal order with deterministic engine/event provenance; not an actual learner action.':'Durable participant order and engine/event provenance.','Scenario packets are fictional source claims, not independent measurements.',...(command.details.observation?['Client-returned snapshot fingerprint exists; attention and understanding are unobserved.']:[])],currency,independentLineages:[...lineages.values()],conflicts,missingEvidence:missing,assumptions:['A report release establishes availability, not whether the participant read it.','Distinct recorded lineages are not proof of independent collection or corroboration.'],alternatives:['A different legal branch may produce a different outcome; no causal comparison has been made in this retrieval.'],wouldChangeIf:['A linked participant explanation, an independently supported correction, or a reviewed alternative practice record is added.','A missing source is restored, or a released correction changes source currency at this cutoff.'],validationStatus:'Source identities and traversal checked; no semantic or instructor acceptance implied',eventLikelihood:'not estimated'};
 return {schema:'replay.decision-retrieval/1',mode:'calculated live retrieval',exerciseId:record.exercise.id,branch:{parentId:record.exercise.parentId??null,forkTick:record.exercise.forkTick??null},side,observedTick:at,graphSha256:hash({nodes,edges}),mappingVersion:options.mapping?.version??'decision-evidence-mapping/1',policy:{maxDepth:2,maxReferences,includeHindsight},seedIds:ids.has(eventId)?[eventId]:[],nodes,edges,nodeIds:visited,edgeIds:[...new Set(traversed)],steps,selectedReferenceIds:visited,sentReferenceIds:[],excerpts:selected.map(n=>({id:n.id,text:n.excerpt,sourceSha256:n.source.sha256,availability:n.availability})),confidence,missingSourceIds:refs.filter(r=>unavailable.has(r.id)).map(r=>r.id)};
}
