/** Bind the registered native model to the local authenticated runtime routing adapter. */
import fs from 'node:fs';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {operatorClient} from './operator-client';import type {KamiwazaClient} from '../../src/platform';
const configure=process.argv.includes('--configure-tomo'),artifact=configure?'evidence/platform/tomo-native-route-config-1.json':'evidence/platform/tomo-native-route-binding-1.json';assert(!fs.existsSync(artifact),'Preserve existing route receipt');
const config=JSON.parse(fs.readFileSync('data/platform/tomo-conversation.json','utf8')),model=JSON.parse(fs.readFileSync('evidence/platform/tomo-provider-deployment-1.json','utf8'));const o=await operatorClient();
try{const client=o.resolved.platformClient as KamiwazaClient;const inventory=await client.request<any>({method:'GET',path:'/serving/deployments'});const rows=Array.isArray(inventory.data)?inventory.data:inventory.data.items??inventory.data.deployments??[];const matches=rows.filter((x:any)=>(x.id??x.deployment_id??x.m_deployment_id)===config.deploymentId);assert.equal(matches.length,1);const row=matches[0];assert.equal(row.m_id??row.model_id,model.modelId);assert.equal(String(row.status).toLowerCase(),'deployed');assert.match(row.serve_path,/^\/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/);assert.equal(row.access_path,`/runtime/models/${config.deploymentId}`);
 const pair={deploymentId:config.deploymentId,servePath:row.serve_path};const proof:any={at:new Date().toISOString(),...pair,modelId:model.modelId,inventoryReceipt:inventory.receipt,inferenceRequests:0};
 if(configure){assert.deepEqual(JSON.parse(fs.readFileSync('data/platform/tomo-native-route.json','utf8')),pair);const cr=JSON.parse(execFileSync('podman',['machine','ssh','kamiwaza-harness-poc','sudo k0s kubectl get kext replay-tomo -n kamiwaza-extensions -o json'],{encoding:'utf8',stdio:['ignore','pipe','pipe']}));const api=cr.spec.services.find((s:any)=>s.name==='api-backend');assert(Array.isArray(api.env));const value='http://replay-server.kamiwaza-extensions.svc.cluster.local:5181/internal/tomo-native-route';const env=api.env.filter((e:any)=>e.name!=='TASKS_PLATFORM_GATEWAY_URL');env.push({name:'TASKS_PLATFORM_GATEWAY_URL',value});const r=await client.request({method:'PATCH',path:'/extensions/replay-tomo',body:{services:[{name:'api-backend',env}]}});proof.previousRoute=api.env.find((e:any)=>e.name==='TASKS_PLATFORM_GATEWAY_URL')?.value;proof.route=value;proof.receipt=r.receipt;proof.note='Local adapter validates member and exact runtime model target with Core ForwardAuth, then forwards to the registered Core serving path. No direct Luna/provider bypass. Other environment values preserved.';
 }else fs.writeFileSync('data/platform/tomo-native-route.json',JSON.stringify(pair),{flag:'wx',mode:0o600});fs.writeFileSync(artifact,JSON.stringify(proof,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(proof));
}finally{o.sessions.close();}
