/** Zero-inference qualification of the local route through native Core model serving. */
import fs from 'node:fs';import assert from 'node:assert/strict';import {KamiwazaClient} from '../../src/platform';
const version=process.argv[2];assert(/^\d+\.\d+\.\d+$/.test(version??''));const artifact=`evidence/platform/tomo-native-route-${version}.json`;assert(!fs.existsSync(artifact));
const b=JSON.parse(fs.readFileSync('data/kamiwaza-binding.json','utf8')),conf=JSON.parse(fs.readFileSync('data/platform/tomo-conversation.json','utf8')),users=JSON.parse(fs.readFileSync('data/platform/team-qualification-users.json','utf8'));const u=users.find((x:any)=>x.role==='commander');let token='';const core=new KamiwazaClient({apiBase:b.apiBase,getToken:()=>token,workroomId:b.workroom.id,forwardedHost:'kamiwaza-harness.localhost'});
try{const build=await(await fetch('http://127.0.0.1:5183/replay-build.json')).json() as any;assert.equal(build.version,version);token=(await core.login({username:u.username,password:u.password})).data.access_token;for(const user of users)user.password='';const entered=await core.enterWorkroom(b.workroom.id);if(entered.data.access_token)token=entered.data.access_token;
 const path=`/internal/tomo-native-route/runtime/models/${conf.deploymentId}/v1/models`,url='http://127.0.0.1:5183'+path;
 const anon=await fetch(url,{signal:AbortSignal.timeout(20000)});assert.equal(anon.status,401);await anon.body?.cancel();
 const r=await fetch(url,{headers:{authorization:'Bearer '+token,'x-workroom-id':b.workroom.id},signal:AbortSignal.timeout(20000)});assert.equal(r.status,200,'Actual registered Core model route unavailable');const data=await r.json() as any;assert.equal(data.data?.[0]?.id,'replay-tomo-luna');const proof={at:new Date().toISOString(),version,sourceSha256:build.sourceArchive.sha256,anonymousStatus:anon.status,memberStatus:r.status,model:data.data[0].id,path,inferenceRequests:0,note:'Normal member bearer → fresh member checks → exact Core model ForwardAuth → registered Core /models. No chat or provider request.'};fs.writeFileSync(artifact,JSON.stringify(proof,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(proof));
}finally{await core.leaveWorkroom();token='';}
