"""Build a standalone, no-network review of a completed, independently verified fictional game."""
import argparse,hashlib,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
p=argparse.ArgumentParser();p.add_argument('trial');args=p.parse_args()
assert re.fullmatch(r'[a-z0-9-]+',args.trial)
base=ROOT/'evidence/dual-model-trial'/args.trial
review_path=ROOT/'evidence/platform'/f'{args.trial}-main-review.json'
review=json.loads(review_path.read_text());assert review['status']=='passed'
summary=json.loads((base/'final/summary.json').read_text());assert summary['config'].get('scenario')=='taiwan-strait/1';assert summary['reconstruction']['finalFingerprint']==review['finalFingerprint'];assert summary['stopReason']=='game-outcome'
provider=json.loads((base/'provider-proof.json').read_text());assert provider['status']=='completed'
rows=[];sources=[]
expected_sources={x["path"]:x["sha256"] for x in summary["sources"]}
def read(rel):
 raw=(base/rel).read_bytes();assert hashlib.sha256(raw).hexdigest()==expected_sources[rel],f'Source changed: {rel}';sources.append({'path':rel,'sha256':hashlib.sha256(raw).hexdigest()});return json.loads(raw)
for n in range(summary['rounds']):
 out=read(f'results/{n:02}/outcome.json');row={'round':n,'fromTick':out['fromTick'],'toTick':out['toTick'],'after':out['board']['after'],'feedback':out['feedback'],'feedbackNote':out['feedbackNote'],'seats':{}}
 for seat in ['blue','red']:
  snap=read(f'rounds/{n:02}/{seat}/snapshot.json');decision=read(f'results/{n:02}/{seat}/decision.json');obs=snap['observation']
  row['seats'][seat]={'resources':obs['ownResources'],'opponentPublic':obs['opponentPublic'],'objectives':obs['objectiveBoard'],'access':obs['access'],'decision':{k:decision.get(k) for k in ['choice','share','intent','meaning','rationale']},'previousDecisions':obs.get('previousDecisions',[]),'fingerprint':snap['fingerprint'],'snapshotId':snap['snapshotId'],'legalNote':obs['legalNote']}
 rows.append(row)
data={'trial':args.trial,'rounds':rows,'outcome':summary['outcome'],'ticks':summary['ticksSimulated'],'providerCalls':review['actualProviderCalls'],'fingerprint':review['finalFingerprint'],'sources':sources}
encoded=json.dumps(data,separators=(',',':')).replace('<','\\u003c').replace('>','\\u003e').replace('&','\\u0026')
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>REPLAY · Taiwan AI match review</title>
<style>
:root{color-scheme:dark;font:16px system-ui,sans-serif;background:#0b1421;color:#eef3f7}*{box-sizing:border-box}body{margin:0}header,main{max-width:1280px;margin:auto;padding:28px}header{border-bottom:1px solid #304050}h1{font-size:34px;letter-spacing:-1px;margin:12px 0}h2{font-size:20px;margin:0 0 18px}h3{font-size:15px;color:#b6c6d5;margin:20px 0 10px}.eyebrow{color:#a1d2cc;font-size:12px;text-transform:uppercase;letter-spacing:2px}.sub{color:#a9b8c8;max-width:920px;line-height:1.6}.badge{display:inline-block;border:1px solid #526375;border-radius:20px;padding:6px 12px;font-size:12px;margin-right:8px}.toolbar{display:flex;align-items:center;gap:16px;flex-wrap:wrap;padding:20px;background:#132235;border-radius:12px}.toolbar input{flex:1;min-width:240px;accent-color:#8dd5cf}button{background:#244057;border:1px solid #58728a;color:inherit;border-radius:6px;padding:9px 14px;cursor:pointer}button:hover{background:#35596d}button:disabled{opacity:.4;cursor:default}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:20px}.card{background:#142233;border:1px solid #2c4155;border-radius:12px;padding:24px}.blue{border-top:4px solid #73b5eb}.red{border-top:4px solid #e3998b}.metrics{display:flex;gap:25px;flex-wrap:wrap}.metric b{display:block;font-size:26px}.metric span,small{font-size:12px;color:#adc0d1}.reason{line-height:1.6;color:#e0e9f0}.label{font-size:12px;color:#a6c4d8;letter-spacing:1px;text-transform:uppercase}.stations{display:flex;gap:8px;flex-wrap:wrap}.station{padding:7px 10px;background:#0b1725;border-radius:5px;font-size:13px}.station.blue-held{color:#9dceff}.station.red-held{color:#f0b0a0}.later{border-left:3px solid #c8b272;padding:12px 16px;background:#211f23;margin-top:20px;line-height:1.6}.muted{color:#a9b8c8}pre{font-size:12px;white-space:pre-wrap;word-break:break-word;max-height:260px;overflow:auto;background:#0b1725;padding:14px}details{margin-top:16px}summary{cursor:pointer;color:#b3cedf}.chart{height:130px;display:flex;gap:5px;align-items:flex-end;padding-top:18px}.chart button{flex:1;min-width:0;padding:0;border:0;border-radius:3px;background:transparent;height:100%;display:flex;align-items:flex-end;gap:2px;outline-offset:3px}.chart i{display:block;width:50%;min-height:2px}.chart .b{background:#73b5eb}.chart .r{background:#e3998b}.chart button[aria-pressed=true]{outline:2px solid white}.callout{padding:16px 20px;background:#192d35;border-radius:8px;line-height:1.6}.footer{margin-top:24px;line-height:1.6;font-size:13px;color:#a5b7c7}code{overflow-wrap:anywhere}@media(max-width:800px){.grid{grid-template-columns:1fr}header,main{padding:18px}h1{font-size:27px}}
</style><header><div class="eyebrow">REPLAY / Saved AI match / Standalone review</div><h1>Taiwan Strait · inside the decisions</h1><p class="sub">Move through the completed match to compare what each player observed, its recorded explanation, and what happened afterward. Regional terrain with fictional forces and relay objectives.</p><span class="badge">Sol · Blue</span><span class="badge">Opus5 · Strait Red cell</span><span class="badge" id="outcome"></span></header>
<main><div class="callout">This was an accelerated offline game: both models chose from the same pre-order state, once per 270 ticks. These are retained decision explanations, not hidden reasoning. This review does not run the game, branch it, or measure learning.</div><div class="chart" id="chart" aria-label="Score after each decision round"></div><p class="muted"><small>Game points after each round · Blue / Red · choose a pair of bars to inspect</small></p><div class="toolbar"><button id="prev">← Previous</button><label for="round">Decision round <strong id="roundLabel"></strong></label><input id="round" type="range" min="0" value="0" step="1"><button id="next">Next →</button><span id="clock"></span></div><div class="grid" id="seats"></div><section class="card" style="margin-top:20px"><h2>Review questions</h2><ul class="reason"><li>What evidence supported the commitment when it was chosen?</li><li>Did the order achieve its intended effect, or was it merely admitted?</li><li>How much did access to relay sites shape the result?</li><li>What would a different decision test? A saved explanation alone does not prove cause.</li></ul><details><summary>Evidence and verification</summary><p id="verification"></p><pre id="sources"></pre></details></section><p class="footer">One match is not evidence of model superiority, balanced geography, human enjoyment or learning efficacy. Blank attack feedback means no effect was recorded by this observer, not that no attack happened. Native continuous exercises and branching remain in the REPLAY app; this is a separate saved-data review.</p></main>
<script id="data" type="application/json">__DATA__</script><script>
const data=JSON.parse(document.getElementById('data').textContent),slider=document.getElementById('round'),fmt=n=>Number(n).toLocaleString('en-US'),el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e};
slider.max=data.rounds.length-1;document.getElementById('outcome').textContent=`${data.outcome.winner==='blue'?'Blue':'Red'} won · Blue ${data.outcome.scores.blue} / Red ${data.outcome.scores.red} · ${data.rounds.length} rounds`;
document.getElementById('verification').textContent=`${data.providerCalls} real model calls. Prompt/reply hashes and final engine reconstruction independently verified. Final tick ${data.ticks}. Fingerprint ${data.fingerprint}. This page projects the original retained artifacts listed below.`;document.getElementById('sources').textContent=JSON.stringify(data.sources,null,2);
const chart=document.getElementById('chart'),max=Math.max(...data.rounds.flatMap(r=>[r.after.scores.blue,r.after.scores.red]),1);
data.rounds.forEach((r,n)=>{const b=el('button');b.setAttribute('aria-label',`Round ${n+1}: Blue ${r.after.scores.blue}, Red ${r.after.scores.red}`);b.title=b.getAttribute('aria-label');for(const s of ['blue','red']){const i=el('i',undefined,s==='blue'?'b':'r');i.style.height=`${r.after.scores[s]/max*100}%`;b.append(i)}b.onclick=()=>{slider.value=n;render()};chart.append(b)});
function render(){const n=Number(slider.value),r=data.rounds[n];document.getElementById('roundLabel').textContent=`${n+1} / ${data.rounds.length}`;document.getElementById('clock').textContent=`Observed tick ${r.fromTick} · ${(r.fromTick/10).toFixed(1)}s`;document.getElementById('prev').disabled=n===0;document.getElementById('next').disabled=n===data.rounds.length-1;[...chart.children].forEach((b,i)=>b.setAttribute('aria-pressed',i===n));const seats=document.getElementById('seats');seats.replaceChildren();
for(const side of ['blue','red']){const s=r.seats[side],card=el('section',undefined,'card '+side);card.append(el('h2',side==='blue'?'Blue · Sol':'Red · Opus5 / Strait cell'),el('p','AVAILABLE AT THE DECISION','label'));const metrics=el('div',undefined,'metrics');for(const [label,value]of [['Troops',s.resources.troops],['Land tiles',s.resources.tiles],['Game points',s.objectives.scores[side]]]){const m=el('div',undefined,'metric');m.append(el('b',fmt(value)),el('span',label));metrics.append(m)}card.append(metrics,el('h3','Relay control at this moment'));const stations=el('div',undefined,'stations');for(const station of s.objectives.stations)stations.append(el('span',`${station.name}${station.priority?' ★':''} · ${station.controller??'uncontrolled'}`,'station '+(station.controller?station.controller+'-held':'')));card.append(stations,el('h3','Selected order'),el('p',s.decision.meaning??'Hold','reason'),el('h3','Recorded explanation'),el('p',s.decision.rationale,'reason'));const after=r.after[side],later=el('div',undefined,'later');later.append(el('strong',`LATER · tick ${r.toTick}`),el('p',`${fmt(after.tiles)} land tiles · ${fmt(after.troops)} troops · ${r.after.scores[side]} game points${after.alive?'':' · eliminated'}`));const feedback=r.feedback[side];later.append(el('p',feedback.length?feedback.map(f=>`${f.status} at ${f.tick}`).join('; '):'No observed effect receipt for this interval. Admission is not proof of success.'));card.append(later);const details=el('details');details.append(el('summary','Inspect exact order and available access'),el('pre',JSON.stringify({snapshot:s.snapshotId,fingerprint:s.fingerprint,intent:s.decision.intent,share:s.decision.share,access:s.access,previousDecisions:s.previousDecisions},null,2)));card.append(details);seats.append(card)}}
slider.oninput=render;document.getElementById('prev').onclick=()=>{slider.value=Number(slider.value)-1;render()};document.getElementById('next').onclick=()=>{slider.value=Number(slider.value)+1;render()};render();
</script></html>'''.replace('__DATA__',encoded)
out=ROOT/'evidence/reviews'/args.trial;out.mkdir(parents=True,exist_ok=False)
(out/'index.html').write_text(html)
receipt={'artifact':str((out/'index.html').relative_to(ROOT)),'sha256':hashlib.sha256(html.encode()).hexdigest(),'rounds':len(rows),'sourceFiles':len(sources),'independentReview':str(review_path.relative_to(ROOT)),'interactiveSavedDataOnly':True,'nativeAppChanged':False,'modelCalls':0}
(out/'receipt.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
