import {afterEach,describe,expect,it,vi} from 'vitest';
import {mkdtempSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {BudgetLedger,LunaClient,type FetchImpl} from '../../src/inference/index';
import {LunaChatClient} from '../../src/inference/luna-chat-client';
import {assertLocalRoute} from '../../src/inference/local-route';
import {readModelRoute} from '../../src/server/model-config';
const cleanup:(()=>void)[]=[];
afterEach(()=>cleanup.splice(0).reverse().forEach(f=>f()));
function fixture(cap=3){const dir=mkdtempSync(join(tmpdir(),'replay-local-'));cleanup.push(()=>rmSync(dir,{recursive:true,force:true}));const ledger=new BudgetLedger({path:join(dir,'local.sqlite'),maxRequests:cap,maxUsd:0});cleanup.push(()=>ledger.close());return {ledger,dir};}
function answer(content='{"finding":"source-linked"}',finish='stop',extras={}){return {id:'chatcmpl_local_1',object:'chat.completion',created:1800000000,model:'muse-glimmer-30b',choices:[{index:0,message:{role:'assistant',content},finish_reason:finish}],usage:{prompt_tokens:120,completion_tokens:30},...extras};}
const endpoint='http://llamacpp-d78470fb.kamiwaza.svc:8080/v1';
const req={instructions:'Use only this fictional exercise',input:'Source: tick 25',purpose:'debrief',jsonSchema:{name:'finding',schema:{type:'object',properties:{finding:{type:'string'}},required:['finding'],additionalProperties:false}}};
describe('explicit local model route',()=>{
 it('uses a separate zero-API ledger and ignores existing paid credentials',()=>{const {dir}=fixture();writeFileSync(join(dir,'luna.env'),'OPENAI_API_KEY=fixture-not-used');const route=readModelRoute(dir,{REPLAY_MODEL_BILLING:'local',REPLAY_MODEL_TRANSPORT:'chat-completions',REPLAY_MODEL_BASE_URL:endpoint,REPLAY_MODEL_ID:'muse-glimmer-30b',OPENAI_API_KEY:'fixture-not-used'});expect(route).toMatchObject({local:true,apiKey:'',ledgerFile:'local-inference.sqlite',maxUsd:0,timeoutMs:120000});expect(readModelRoute(dir,{})).toMatchObject({local:false,ledgerFile:'inference.sqlite',maxUsd:5});});
 it.each(['https://api.openai.com/v1','https://example.com/v1','http://user:password@127.0.0.1/v1','http://127.0.0.1/v1?key=secret'])('rejects unqualified local endpoint %s',url=>expect(()=>assertLocalRoute(url,'model')).toThrow());
 it('requires an explicit model and transport before touching a ledger',()=>{const {dir}=fixture();expect(()=>readModelRoute(dir,{REPLAY_MODEL_BILLING:'local'})).toThrow();expect(()=>assertLocalRoute(endpoint,undefined)).toThrow();});
 it('reserves first, sends strict Chat JSON, records real usage and enforces count cap at zero dollars',async()=>{
  const {ledger}=fixture(1);const fetchImpl=vi.fn<FetchImpl>(async(url,init)=>{expect(ledger.listReceipts()[0]?.status).toBe('reserved');expect(url).toBe(endpoint+'/chat/completions');expect(init.redirect).toBe('error');expect(new Headers(init.headers).has('authorization')).toBe(false);expect(JSON.parse(String(init.body))).toMatchObject({model:'muse-glimmer-30b',max_tokens:1000,response_format:{type:'json_schema',json_schema:{name:'finding',schema:req.jsonSchema.schema,strict:true}}});return new Response(JSON.stringify(answer()));});
  const client=new LunaClient({local:true,apiKey:'',ledger,baseUrl:endpoint,model:'muse-glimmer-30b',fetchImpl});const result=await client.complete(req);
  expect(result.parsed).toEqual({finding:'source-linked'});expect(result.receipt).toMatchObject({status:'completed',reservedMicro:0,settledMicro:0,inputTokens:120,outputTokens:30,modelReturned:'muse-glimmer-30b',context:{inferenceRoute:'kamiwaza-local'}});
  await expect(client.complete(req)).rejects.toBeDefined();expect(fetchImpl).toHaveBeenCalledTimes(1);expect(ledger.summary()).toMatchObject({requestsUsed:1,committedMicro:0});
 });
 it.each(['length','tool_calls','content_filter'])('does not apply unusable output (%s) even if JSON parses',async finish=>{const {ledger}=fixture();const fetchImpl=vi.fn<FetchImpl>(async()=>new Response(JSON.stringify(answer('{}',finish))));const client=new LunaClient({local:true,apiKey:'',ledger,baseUrl:endpoint,model:'muse-glimmer-30b',fetchImpl});await expect(client.complete(req)).rejects.toMatchObject({code:'incomplete_response'});expect(fetchImpl).toHaveBeenCalledTimes(1);expect(ledger.summary().requestsUsed).toBe(1);});
 it('retains an uncertain counted receipt when provider usage is absent',async()=>{const {ledger}=fixture();const client=new LunaClient({local:true,apiKey:'',ledger,baseUrl:endpoint,model:'muse-glimmer-30b',fetchImpl:async()=>new Response(JSON.stringify(answer('{}','stop',{usage:null})))});await client.complete(req);expect(ledger.listReceipts()[0]).toMatchObject({status:'uncertain',errorCode:'usage_missing',reservedMicro:0});});
 it('makes one attempt and never falls back to an external API on network failure',async()=>{const {ledger}=fixture();const fetchImpl=vi.fn<FetchImpl>(async()=>{throw new Error('offline');});const client=new LunaClient({local:true,apiKey:'',ledger,baseUrl:endpoint,model:'muse-glimmer-30b',fetchImpl});await expect(client.complete(req)).rejects.toMatchObject({code:'network_error'});expect(fetchImpl).toHaveBeenCalledTimes(1);expect(ledger.listReceipts()[0]).toMatchObject({status:'uncertain',reservedMicro:0});});
 it('supports the bounded chat/tool pipeline locally without treating an empty key as a secret substring',async()=>{const {ledger}=fixture();const fetchImpl=vi.fn<FetchImpl>(async(_url,init)=>{const body=JSON.parse(String(init.body));expect(body.max_tokens).toBe(1000);expect(body).not.toHaveProperty('reasoning_effort');return new Response(JSON.stringify(answer('Known at tick 25')));});const client=new LunaChatClient({local:true,apiKey:'',ledger,baseUrl:endpoint,model:'muse-glimmer-30b',fetchImpl});const result=await client.complete({messages:[{role:'user',content:'What was known?'}],tools:[],purpose:'tomo.chat',context:{tick:25}});expect(result.receipt).toMatchObject({status:'completed',modelReturned:'muse-glimmer-30b',settledMicro:0,inputTokens:120});});
});
